### ISSUE TITLE
Adapt for Pester V5

### ISSUE THREAD

**Issue by Sarafian** [Sarafian/MarkdownPS#25]
Also update appveyor secure key

**Comment by belibug** [comment]
> Also update appveyor secure key

Consider moving to Github Actions, much simpler CI/CD. Both code and actions will remain in same platform.

**Comment by Sarafian** [comment]
Github actions are outside my bandwidth at this moment. 
If you want, please investigate but please keep in mind that all the powershell repositories are derived from this template
https://github.com/Sarafian/PowerShellTemplate

So maybe that would be the best place to start.

**Comment by belibug** [comment]
I understand. 

Quick question, how is the release process managed? I may be misunderstanding how AppVeyor works. Is the publication to the PowerShell Gallery controlled based on tags? If so, I did not see any reference to that in the YAML file.

**Comment by Sarafian** [comment]
There is more information in the https://github.com/Sarafian/PowerShellTemplate. I also saw there that the Pester v5 changes were significant and need refactoring with the test scripts. There is an [issue](https://github.com/Sarafian/PowerShellTemplate/issues/5) for this as well there. That's why I didn't complete it here in the first place.

The appveyor is light weight CI/CD provider which is driven by the yaml file you see on the root. It reacts to events from github. it will always run the tests but it will only publish from master. Currently, the publishing regime is manually controlled by code and I've not figured that one out. When should it increment the minor version or go for a new major. Currently the version is in `.psm1` file. The publish script, generates a temporary `.psd1` file to drive the publishing. I always had troubles with the `.psd1` being source controlled, hence this trick. If you want, we can chat more in gitter (link on readme)

Now, the pester changes seem big and might not be easy. Up to you if you want to pick up the challenge. If you just want to implement the cmdlet, do it assuming Pester v4 and we will fix all with the v5 adaptation.

**Comment by Sarafian** [comment]
Done
