### ISSUE TITLE
Found Security Issue

### ISSUE THREAD

**Issue by belibug** [Sarafian/MarkdownPS#32]
Hey, would a security bug that I dont want to disclose on public forum. How do I reach you/update you.

**Comment by Sarafian** [comment]
I find strange that there can be a security bug for such a module given it's functionality that is to render markdown text.
Maybe it's about the CI pipeline and the appveyor's config key. If yes, then lets continue on gitter.

**Comment by Sarafian** [comment]
Apparently you can retrieve one's email 
There are multiple ways and if you ask me, oups and scary.
Check out this [link](https://webapps.stackexchange.com/questions/29197/any-way-to-contact-a-user-on-github) from stackoverflow. There is even website for it :) :)

In [my github pages](https://sarafian.github.io/) you can also see me contacts. I guess linkedin message?

**Comment by belibug** [comment]
Contacted you on Linkedin, I might be wrong, but still wanted to make sure you are aware of the issue.

**Comment by Sarafian** [comment]
Cleared out. Thanks.
