### ISSUE TITLE
Syntax of Line in New-MDQuote

### ISSUE THREAD

**Issue by belibug** [Sarafian/MarkdownPS#33]
This is how it currently works

```
 New-MDQuote -Lines @("Line 1","Line 2")

> Line 1
> 
> Line 2
```

Why the blank line between Line1 and Line2.

I checked the syntax guide [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-text) which doesn't have multiline example.

This is another [doc link](https://www.markdownguide.org/basic-syntax/#nested-blockquotes) with multi line and nested quotes. They don't required empty "> " line between lines either.

**Comment by Sarafian** [comment]
I'm not sure. One hypothesis I can make is that when this was developed, one markdown rendered didn't play nice and I had to do it like that. Could be just as well me being silly and this is bug. Let's go with the bug.

**Comment by Sarafian** [comment]
The issue seems to be with the following lines

```powershell
            if($output -ne "")
            {
                $output+="$prefix"+[System.Environment]::NewLine
            }
```

I'm not sure what was the reasoning behind this.

**Comment by Sarafian** [comment]
**Let's go with the bug.**
